name: podkes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/1.png
  - assets/2.png
  - assets/3.png
  - assets/4.png
  - assets/betmoji.png
  - assets/girl.png
  - assets/Notification.png
  - assets/pod1.png
  - assets/pod2.png
  - assets/pod3.png
  - assets/profile1.png
  - assets/profile2.png
  - assets/profile3.png
  - assets/profile4.png
  - assets/arrow.png
  - assets/drawer.png
  - assets/Search.png
  - assets/explore.png
  - assets/exploreWhite.png
  - assets/library.png
  - assets/libraryWhite.png
  - assets/profile.png
  - assets/profileWhite.png
  - assets/play.png
  - assets/fooo.png
  
